name: abcde-testing
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- jupyter
- jupyterlab
- conda
- scikit-learn
- scipy
- pandas
- numpy
- matplotlib
- seaborn
- theano
- bokeh
- holoviews
- pymc3
- pyjanitor
- flake8
- mypy
